# Array Creation

The functions listed below are designed to create `array` or `Quantity` with specific properties, such as filled with a certain value, identity matrices, or arrays with ones on the diagonal. These functions are part of the `brainunit.math` module and are tailored to handle both numerical `array` and `Quantity` with units.

In [17]:
import brainunit as bu
import brainunit.math as bm
import jax.numpy as jnp

## Full (`brainunit.math.full`)
Returns a quantity or array filled with a specific value.

In [6]:
array = bm.full(3, 4)                   # return a jax.Array
quantity = bm.full(3, 4 * bu.second)    # return a Quantity

array, quantity

(Array([4, 4, 4], dtype=int32, weak_type=True),
 ArrayImpl([4., 4., 4.], dtype=float32) * second)

## Empty (`brainunit.math.empty`)
Return a new quantity or array of given shape and type, without initializing entries.

In [10]:
array = bm.empty((2, 2))                    # return a jax.Array
quantity = bm.empty((2, 2), unit=bu.second) # return a Quantity

array, quantity

(Array([[0., 0.],
        [0., 0.]], dtype=float32),
 ArrayImpl([[0., 0.],
            [0., 0.]], dtype=float32) * second)

## Ones (`brainunit.math.ones`)
Returns a new quantity or array of given shape and type, filled with ones.

In [11]:
array = bm.ones((2, 2))                     # return a jax.Array
quantity = bm.ones((2, 2), unit=bu.second)  # return a Quantity

array, quantity

(Array([[1., 1.],
        [1., 1.]], dtype=float32),
 ArrayImpl([[1., 1.],
            [1., 1.]], dtype=float32) * second)

## Zeros (`brainunit.math.zeros`)
Returns a new quantity or array of given shape and type, filled with ones.

In [12]:
array = bm.zeros((2, 2))                    # return a jax.Array
quantity = bm.zeros((2, 2), unit=bu.second) # return a Quantity

array, quantity

(Array([[0., 0.],
        [0., 0.]], dtype=float32),
 ArrayImpl([[0., 0.],
            [0., 0.]], dtype=float32) * second)

## Eye (`brainunit.math.eye`)
Returns a 2-D quantity or array with ones on the diagonal and zeros elsewhere.

In [7]:
array = bm.eye(3)                       # return a jax.Array
quantity = bm.eye(3, unit=bu.second)    # return a Quantity

array, quantity

(Array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32),
 ArrayImpl([[1., 0., 0.],
            [0., 1., 0.],
            [0., 0., 1.]], dtype=float32) * second)

## Identity (`brainunit.math.identity`)
Return the identity Quantity or array.

In [8]:
array = bm.identity(3)                  # return a jax.Array
quantity = bm.identity(3, unit=bu.second)    # return a Quantity

array, quantity

(Array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32),
 ArrayImpl([[1., 0., 0.],
            [0., 1., 0.],
            [0., 0., 1.]], dtype=float32) * second)

## Tri (`brainunit.math.tri`)
Returns A quantity or an array with ones at and below the given diagonal and zeros elsewhere.


In [9]:
array = bm.tri(3)                       # return a jax.Array
quantity = bm.tri(3, unit=bu.second)    # return a Quantity

array, quantity

(Array([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]], dtype=float32),
 ArrayImpl([[1., 0., 0.],
            [1., 1., 0.],
            [1., 1., 1.]], dtype=float32) * second)

## Array & Asarray (`brainunit.math.array`, `brainunit.math.asarray`)
Convert the input to a quantity or array.

  If unit is provided, the input will be checked whether it has the same unit as the provided unit.
  (If they have same dimension but different magnitude, the input will be converted to the provided unit.)
  If unit is not provided, the input will be converted to an array.


In [14]:
array = bm.asarray([1, 2, 3])                       # return a jax.Array
quantity = bm.asarray([1, 2, 3], unit=bu.second)    # return a Quantity

array, quantity

(Array([1, 2, 3], dtype=int32),
 ArrayImpl([1., 2., 3.], dtype=float32) * second)

In [15]:
# check if the input has the same unit as the provided unit
a = bm.asarray([1 * bu.second, 2 * bu.second], unit=bu.second)
a

ArrayImpl([1., 2.], dtype=float32) * second

In [16]:
# fails because the input has a different unit
try:
    b = bm.asarray([1 * bu.second, 2 * bu.second], unit=bu.ampere)
except Exception as e:
    print(e)

a and unit have to have the same units. (unit is s).


## Full like (`brainunit.math.full_like`)
Return a new quantity or array with the same shape and type as a given array or quantity, filled with `fill_value`.


In [18]:
a = jnp.array([1, 2, 3])

array = bm.full_like(a, 4)                       # return a jax.Array
quantity = bm.full_like(a, 4 * bu.second)         # return a Quantity

array, quantity

(Array([4, 4, 4], dtype=int32),
 ArrayImpl([4., 4., 4.], dtype=float32) * second)

## Empty like (`brainunit.math.empty_like`)
Return a new quantity or array with the same shape and type as a given array.


In [23]:
a = jnp.array([1, 2, 3])
q = jnp.array([1, 2, 3]) * bu.second

array = bm.empty_like(a)       # return a jax.Array
quantity = bm.empty_like(q)    # return a Quantity

array, quantity

(Array([0, 0, 0], dtype=int32),
 ArrayImpl([0., 0., 0.], dtype=float32) * second)

## Ones like (`brainunit.math.ones_like`)
Return a new quantity or array with the same shape and type as a given array, filled with ones.

In [24]:
a = jnp.array([1, 2, 3])
q = jnp.array([1, 2, 3]) * bu.second

array = bm.ones_like(a)       # return a jax.Array
quantity = bm.ones_like(q)    # return a Quantity

array, quantity

(Array([1, 1, 1], dtype=int32),
 ArrayImpl([1., 1., 1.], dtype=float32) * second)

## Zeros like (`brainunit.math.zeros_like`)
Return a new quantity or array with the same shape and type as a given array, filled with zeros.

In [25]:
a = jnp.array([1, 2, 3])
q = jnp.array([1, 2, 3]) * bu.second

array = bm.zeros_like(a)       # return a jax.Array
quantity = bm.zeros_like(q)    # return a Quantity

array, quantity

(Array([0, 0, 0], dtype=int32),
 ArrayImpl([0., 0., 0.], dtype=float32) * second)

## Fill diagonal (`brainunit.math.fill_diagonal`)
Fill the main diagonal of the given array of any dimensionality.

In [32]:
a = jnp.zeros((3, 3))
q = jnp.zeros((3, 3)) * bu.second

array = bm.fill_diagonal(a, 4)      # return a jax.Array
quantity = bm.fill_diagonal(q, 4 * bu.second)   # return a Quantity

array, quantity

(Array([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]], dtype=float32),
 ArrayImpl([[4., 0., 0.],
            [0., 4., 0.],
            [0., 0., 4.]], dtype=float32) * second)

## Diag (`brainunit.math.diag`)
Extract a diagonal or construct a diagonal array.

In [19]:
a = jnp.array([1, 2, 3])

array = bm.diag(a)                       # return a jax.Array
quantity = bm.diag(a, unit=bu.second)    # return a Quantity

array, quantity

(Array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]], dtype=int32),
 ArrayImpl([[1., 0., 0.],
            [0., 2., 0.],
            [0., 0., 3.]], dtype=float32) * second)

## Tril (`brainunit.math.tril`)
Lower triangle of an array.

  Return a copy of a matrix with the elements above the `k`-th diagonal zeroed.
  For quantities or arrays with ``ndim`` exceeding 2, `tril` will apply to the final two axes.


In [21]:
a = jnp.ones((3, 3))

array = bm.diag(a)                       # return a jax.Array
quantity = bm.diag(a, unit=bu.second)    # return a Quantity

array, quantity

(Array([1., 1., 1.], dtype=float32),
 ArrayImpl([1., 1., 1.], dtype=float32) * second)

## Triu (`brainunit.math.triu`)
Upper triangle of an array.

  Return a copy of a matrix with the elements below the `k`-th diagonal zeroed.
  For quantities or arrays with ``ndim`` exceeding 2, `triu` will apply to the final two axes.

In [22]:
a = jnp.ones((3, 3))

array = bm.tril(a)                       # return a jax.Array
quantity = bm.tril(a, unit=bu.second)    # return a Quantity

array, quantity

(Array([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]], dtype=float32),
 ArrayImpl([[1., 0., 0.],
            [1., 1., 0.],
            [1., 1., 1.]], dtype=float32) * second)

## Arange (`brainunit.math.arange`)
Return evenly spaced values within a given interval.

In [26]:
array = bm.arange(5)                                    # return a jax.Array
quantity = bm.arange(5 * bu.second, step=1 * bu.second) # return a Quantity

array, quantity

(Quantity(ArrayImpl([0., 1., 2., 3., 4.], dtype=float32)),
 ArrayImpl([0., 1., 2., 3., 4.], dtype=float32) * second)

In [28]:
array = bm.arange(3, 9, 1)                                          # return a jax.Array
quantity = bm.arange(3 * bu.second, 9 * bu.second, 1 * bu.second)   # return a Quantity

array, quantity

(Quantity(ArrayImpl([3., 4., 5., 6., 7., 8.], dtype=float32)),
 ArrayImpl([3., 4., 5., 6., 7., 8.], dtype=float32) * second)

## Linspace (`brainunit.math.linspace`)
Return evenly spaced numbers over a specified interval.

In [30]:
array = bm.linspace(0, 10, 5)                               # return a jax.Array
quantity = bm.linspace(0 * bu.second, 10 * bu.second, 5)    # return a Quantity

array, quantity

(Quantity(ArrayImpl([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32)),
 ArrayImpl([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32) * second)

## Logspace (`brainunit.math.logspace`)
Return numbers spaced evenly on a log scale.

In [31]:
array = bm.logspace(0, 10, 5)                               # return a jax.Array
quantity = bm.logspace(0 * bu.second, 10 * bu.second, 5)    # return a Quantity

array, quantity

(Quantity(ArrayImpl([1.0000000e+00, 3.1622775e+02, 1.0000000e+05, 3.1622776e+07,
            1.0000000e+10], dtype=float32)),
 ArrayImpl([1.0000000e-03, 3.1622776e-01, 1.0000000e+02, 3.1622775e+04,
            1.0000000e+07], dtype=float32) * ksecond)

## Array split (`brainunit.math.array_split`)
Split an array into multiple sub-arrays.

In [33]:
a = jnp.arange(9)
q = jnp.arange(9) * bu.second

array = bm.array_split(a, 3)      # return a jax.Array
quantity = bm.array_split(q, 3)   # return a Quantity

array, quantity

([Array([0, 1, 2], dtype=int32),
  Array([3, 4, 5], dtype=int32),
  Array([6, 7, 8], dtype=int32)],
 [ArrayImpl([0., 1., 2.], dtype=float32) * second,
  ArrayImpl([3., 4., 5.], dtype=float32) * second,
  ArrayImpl([6., 7., 8.], dtype=float32) * second])

## Meshgrid (`brainunit.math.meshgrid`)
Return coordinate matrices from coordinate vectors.

In [34]:
x = jnp.array([1, 2, 3])
y = jnp.array([4, 5])
x_q = jnp.array([1, 2, 3]) * bu.second
y_q = jnp.array([4, 5]) * bu.second

array = bm.meshgrid(x, y)           # return a jax.Array
quantity = bm.meshgrid(x_q, y_q)    # return a Quantity

array, quantity

([Array([[1, 2, 3],
         [1, 2, 3]], dtype=int32),
  Array([[4, 4, 4],
         [5, 5, 5]], dtype=int32)],
 [ArrayImpl([[1., 2., 3.],
             [1., 2., 3.]], dtype=float32) * second,
  ArrayImpl([[4., 4., 4.],
             [5., 5., 5.]], dtype=float32) * second])

## Vandermode (`brainunit.math.vander`)
Generate a Vandermonde matrix.

The Vandermonde matrix is a matrix with the terms of a geometric progression in each row.
  The geometric progression is defined by the vector `x` and the number of columns `N`.


In [36]:
a = jnp.array([1, 2, 3])
q = jnp.array([1, 2, 3]) * bu.second

array = bm.vander(a)                       # return a jax.Array
quantity = bm.vander(q)    # return a Quantity

array, quantity

(Array([[1, 1, 1],
        [4, 2, 1],
        [9, 3, 1]], dtype=int32),
 ArrayImpl([[1., 1., 1.],
            [4., 2., 1.],
            [9., 3., 1.]], dtype=float32) * second)