# Array Creation

[![Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/chaoming0625/brainunit/blob/master/docs/mathematical_functions/array_creation.ipynb)
[![Open in Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://kaggle.com/kernels/welcome?src=https://github.com/chaoming0625/brainunit/blob/master/docs/mathematical_functions/array_creation.ipynb)

The functions listed below are designed to create `array` or `Quantity` with specific properties, such as filled with a certain value, identity matrices, or arrays with ones on the diagonal. These functions are part of the `brainunit.math` module and are tailored to handle both numerical `array` and `Quantity` with units.

In [1]:
import brainunit as bu
import brainunit.math as bm
import jax.numpy as jnp

## `brainunit.math.array` & `brainunit.math.asarray`

Convert the input to a quantity or array.

  If unit is provided, the input will be checked whether it has the same unit as the provided unit.
  (If they have same dimension but different magnitude, the input will be converted to the provided unit.)
  If unit is not provided, the input will be converted to an array.

In [ ]:
bm.asarray([1, 2, 3])                       # return a jax.Array

Array([1, 2, 3], dtype=int32)

In [ ]:
bm.asarray([1, 2, 3], unit=bu.second)    # return a Quantity

ArrayImpl([1., 2., 3.], dtype=float32) * second

In [ ]:
# check if the input has the same unit as the provided unit
bm.asarray([1 * bu.second, 2 * bu.second], unit=bu.second)

ArrayImpl([1., 2.], dtype=float32) * second

In [ ]:
# fails because the input has a different unit
try:
    bm.asarray([1 * bu.second, 2 * bu.second], unit=bu.ampere)
except Exception as e:
    print(e)

a and unit have to have the same units. (unit is s).


## `brainunit.math.arange`
Return evenly spaced values within a given interval.

In [ ]:
bm.arange(5)                                    # return a jax.Array

Quantity(ArrayImpl([0., 1., 2., 3., 4.], dtype=float32))

In [ ]:
bm.arange(5 * bu.second, step=1 * bu.second) # return a Quantity

ArrayImpl([0., 1., 2., 3., 4.], dtype=float32) * second

In [ ]:
bm.arange(3, 9, 1)                                          # return a jax.Array

Quantity(ArrayImpl([3., 4., 5., 6., 7., 8.], dtype=float32))

In [ ]:
bm.arange(3 * bu.second, 9 * bu.second, 1 * bu.second)   # return a Quantity

ArrayImpl([3., 4., 5., 6., 7., 8.], dtype=float32) * second

## `brainunit.math.array_split`
Split an array into multiple sub-arrays.

In [ ]:
a = jnp.arange(9)

bm.array_split(a, 3)      # return a jax.Array

[Array([0, 1, 2], dtype=int32),
 Array([3, 4, 5], dtype=int32),
 Array([6, 7, 8], dtype=int32)]

In [ ]:
q = jnp.arange(9) * bu.second

bm.array_split(q, 3)   # return a Quantity

[ArrayImpl([0., 1., 2.], dtype=float32) * second,
 ArrayImpl([3., 4., 5.], dtype=float32) * second,
 ArrayImpl([6., 7., 8.], dtype=float32) * second]

## `brainunit.math.linspace`
Return evenly spaced numbers over a specified interval.

In [ ]:
bm.linspace(0, 10, 5)                               # return a jax.Array

Quantity(ArrayImpl([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32))

In [ ]:
bm.linspace(0 * bu.second, 10 * bu.second, 5)    # return a Quantity

ArrayImpl([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32) * second

## `brainunit.math.logspace`
Return numbers spaced evenly on a log scale.

In [ ]:
bm.logspace(0, 10, 5)                               # return a jax.Array

Quantity(ArrayImpl([1.0000000e+00, 3.1622775e+02, 1.0000000e+05, 3.1622776e+07,
           1.0000000e+10], dtype=float32))

In [ ]:
bm.logspace(0 * bu.second, 10 * bu.second, 5)    # return a Quantity

ArrayImpl([1.0000000e-03, 3.1622776e-01, 1.0000000e+02, 3.1622775e+04,
           1.0000000e+07], dtype=float32) * ksecond

## `brainunit.math.meshgrid`
Return coordinate matrices from coordinate vectors.

In [ ]:
x = jnp.array([1, 2, 3])
y = jnp.array([4, 5])

bm.meshgrid(x, y)           # return a jax.Array

[Array([[1, 2, 3],
        [1, 2, 3]], dtype=int32),
 Array([[4, 4, 4],
        [5, 5, 5]], dtype=int32)]

In [ ]:
x_q = jnp.array([1, 2, 3]) * bu.second
y_q = jnp.array([4, 5]) * bu.second

bm.meshgrid(x_q, y_q)    # return a Quantity

[ArrayImpl([[1., 2., 3.],
            [1., 2., 3.]], dtype=float32) * second,
 ArrayImpl([[4., 4., 4.],
            [5., 5., 5.]], dtype=float32) * second]

## `brainunit.math.vander`
Generate a Vandermonde matrix.

The Vandermonde matrix is a matrix with the terms of a geometric progression in each row.
  The geometric progression is defined by the vector `x` and the number of columns `N`.


In [ ]:
a = jnp.array([1, 2, 3])

bm.vander(a)                       # return a jax.Array

Array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]], dtype=int32)

In [ ]:
q = jnp.array([1, 2, 3]) * bu.second

bm.vander(q)    # return a Quantity

ArrayImpl([[1., 1., 1.],
           [4., 2., 1.],
           [9., 3., 1.]], dtype=float32) * second

## Can use with `Quantity`

The functions below can be used with `Quantity` with units.

### `brainunit.math.full`
Returns a quantity or array filled with a specific value.

In [2]:
bm.full(3, 4)                   # return a jax.Array

Array([4, 4, 4], dtype=int32, weak_type=True)

In [3]:
bm.full(3, 4 * bu.second)    # return a Quantity

ArrayImpl([4., 4., 4.], dtype=float32) * second

### `brainunit.math.empty`
Return a new quantity or array of given shape and type, without initializing entries.

In [4]:
bm.empty((2, 2))                    # return a jax.Array

Array([[0., 0.],
       [0., 0.]], dtype=float32)

In [5]:
bm.empty((2, 2), unit=bu.second) # return a Quantity

ArrayImpl([[0., 0.],
           [0., 0.]], dtype=float32) * second

### `brainunit.math.ones`
Returns a new quantity or array of given shape and type, filled with ones.

In [6]:
bm.ones((2, 2))                     # return a jax.Array

Array([[1., 1.],
       [1., 1.]], dtype=float32)

In [7]:
bm.ones((2, 2), unit=bu.second)  # return a Quantity

ArrayImpl([[1., 1.],
           [1., 1.]], dtype=float32) * second

### `brainunit.math.zeros`
Returns a new quantity or array of given shape and type, filled with ones.

In [8]:
bm.zeros((2, 2))                    # return a jax.Array

Array([[0., 0.],
       [0., 0.]], dtype=float32)

In [9]:
bm.zeros((2, 2), unit=bu.second) # return a Quantity

ArrayImpl([[0., 0.],
           [0., 0.]], dtype=float32) * second

### `brainunit.math.full_like`
Return a new quantity or array with the same shape and type as a given array or quantity, filled with `fill_value`.


In [ ]:
a = jnp.array([1, 2, 3])

bm.full_like(a, 4)                       # return a jax.Array

Array([4, 4, 4], dtype=int32)

In [ ]:
bm.full_like(a, 4 * bu.second)         # return a Quantity

ArrayImpl([4., 4., 4.], dtype=float32) * second

### `brainunit.math.empty_like`
Return a new quantity or array with the same shape and type as a given array.


In [ ]:
a = jnp.array([1, 2, 3])

bm.empty_like(a)       # return a jax.Array

Array([0, 0, 0], dtype=int32)

In [ ]:
q = jnp.array([1, 2, 3]) * bu.second

bm.empty_like(q)    # return a Quantity

ArrayImpl([0., 0., 0.], dtype=float32) * second

### `brainunit.math.ones_like`
Return a new quantity or array with the same shape and type as a given array, filled with ones.

In [ ]:
a = jnp.array([1, 2, 3])

bm.ones_like(a)       # return a jax.Array

Array([1, 1, 1], dtype=int32)

In [ ]:
q = jnp.array([1, 2, 3]) * bu.second

bm.ones_like(q)    # return a Quantity

ArrayImpl([1., 1., 1.], dtype=float32) * second

### `brainunit.math.zeros_like`
Return a new quantity or array with the same shape and type as a given array, filled with zeros.

In [ ]:
a = jnp.array([1, 2, 3])

bm.zeros_like(a)       # return a jax.Array

Array([0, 0, 0], dtype=int32)

In [ ]:
q = jnp.array([1, 2, 3]) * bu.second

bm.zeros_like(q)    # return a Quantity

ArrayImpl([0., 0., 0.], dtype=float32) * second

### `brainunit.math.fill_diagonal`
Fill the main diagonal of the given array of any dimensionality.

In [ ]:
a = jnp.zeros((3, 3))

bm.fill_diagonal(a, 4)      # return a jax.Array

Array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]], dtype=float32)

In [ ]:
q = jnp.zeros((3, 3)) * bu.second

bm.fill_diagonal(q, 4 * bu.second)   # return a Quantity

ArrayImpl([[4., 0., 0.],
           [0., 4., 0.],
           [0., 0., 4.]], dtype=float32) * second

## Can use with `unit` keyword

The functions below can be used with the `unit` keyword.

### `brainunit.math.eye`
Returns a 2-D quantity or array with ones on the diagonal and zeros elsewhere.

In [10]:
bm.eye(3)                       # return a jax.Array

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [11]:
bm.eye(3, unit=bu.second)    # return a Quantity

ArrayImpl([[1., 0., 0.],
           [0., 1., 0.],
           [0., 0., 1.]], dtype=float32) * second

### `brainunit.math.identity`
Return the identity Quantity or array.

In [12]:
bm.identity(3)                  # return a jax.Array

Array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [13]:
bm.identity(3, unit=bu.second)    # return a Quantity

ArrayImpl([[1., 0., 0.],
           [0., 1., 0.],
           [0., 0., 1.]], dtype=float32) * second

### `brainunit.math.tri`
Returns A quantity or an array with ones at and below the given diagonal and zeros elsewhere.


In [14]:
bm.tri(3)                       # return a jax.Array

Array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]], dtype=float32)

In [15]:
bm.tri(3, unit=bu.second)    # return a Quantity

ArrayImpl([[1., 0., 0.],
           [1., 1., 0.],
           [1., 1., 1.]], dtype=float32) * second

### `brainunit.math.diag`
Extract a diagonal or construct a diagonal array.

In [30]:
a = jnp.array([1, 2, 3])

bm.diag(a)                       # return a jax.Array

Array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]], dtype=int32)

In [31]:
bm.diag(a, unit=bu.second)    # return a Quantity

ArrayImpl([[1., 0., 0.],
           [0., 2., 0.],
           [0., 0., 3.]], dtype=float32) * second

### `brainunit.math.tril`
Lower triangle of an array.

  Return a copy of a matrix with the elements above the `k`-th diagonal zeroed.
  For quantities or arrays with ``ndim`` exceeding 2, `tril` will apply to the final two axes.


In [32]:
a = jnp.ones((3, 3))

bm.diag(a)                       # return a jax.Array

Array([1., 1., 1.], dtype=float32)

In [33]:
bm.diag(a, unit=bu.second)    # return a Quantity

ArrayImpl([1., 1., 1.], dtype=float32) * second

### `brainunit.math.triu`
Upper triangle of an array.

  Return a copy of a matrix with the elements below the `k`-th diagonal zeroed.
  For quantities or arrays with ``ndim`` exceeding 2, `triu` will apply to the final two axes.

In [34]:
a = jnp.ones((3, 3))

bm.tril(a)                       # return a jax.Array

Array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]], dtype=float32)

In [35]:
bm.tril(a, unit=bu.second)    # return a Quantity

ArrayImpl([[1., 0., 0.],
           [1., 1., 0.],
           [1., 1., 1.]], dtype=float32) * second