# NumPy Functions

In `brainunit.math` we reimplemented almost all important NumPy functions compatible with both `Quantity` and arrays.
For compatible with `Quantity`, we categorized the functions into serveral groups.

- [Array Creation](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#array-creation)
- [Array Manipulation](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#array-manipulation)
- [Functions Accept Unitless](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#functions-accept-unitless)
- [Functions with Bitwise Operations](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#functions-with-bitwise-operations)
- [Functions Changing Unit](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#functions-changing-unit)
- [Indexing Functions](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#indexing-functions)
- [Functions Keeping Unit](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#functions-keeping-unit)
- [Logical Functions](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#logical-functions)
- [Functions Matching Unit](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#functions-matching-unit)
- [Functions Removing Unit](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#functions-removing-unit)
- [Window Functions](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#window-functions)
- [Get Attribute Functions](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#get-attribute-functions)
- [Linear Algebra Functions](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#linear-algebra-functions)
- [More Functions](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html#more-functions)

Detailed information can be found in the [API documentation](https://brainunit.readthedocs.io/en/latest/apis/brainunit.math.html).

### Array Creation

In [41]:
import brainunit as bu
import brainunit.math as bm
import jax.numpy as jnp
import brainstate as bst
bst.environ.set(precision=64)

In [42]:
bm.full(3, 4 * bu.second)

ArrayImpl([4., 4., 4.]) * second

### Array Manipulation

In [43]:
q = [1, 2, 3, 4] * bu.second
bu.math.reshape(q, (2, 2))

ArrayImpl([[1., 2.],
           [3., 4.]]) * second

### Function: Accept Unitless

In [44]:
q = [1.0, 2.0] * bu.second
bm.exp(q.to_value(bu.second))

Array([2.71828183, 7.3890561 ], dtype=float64)

### Function: Bitwise Operations

In [45]:
q = jnp.array([0b1100]) * bu.second
bm.invert(q.to_value(bu.second).astype(jnp.int32))

Array([-13], dtype=int32)

### Function: Change Unit

In [46]:
q1 = [1, 2] * bu.ms
q2 = [3, 4] * bu.mV
bm.multiply(q1, q2)

ArrayImpl([3., 8.]) * uweber

### Function: Indexing

In [47]:
q = [1, 2, 3, 4, 5] * bu.second
bm.where(q > 2 * bu.second, q, 0)

ArrayImpl([0., 0., 3., 4., 5.]) * second

### Function: Keep Unit

In [48]:
q = [-1, -2, 3] * bu.ms
bm.abs(q)

ArrayImpl([1., 2., 3.]) * msecond

### Function: Matching Unit

In [49]:
q1 = [1, 2] * bu.ms
q2 = [3, 4] * bu.ms
bm.add(q1, q2)

ArrayImpl([4., 6.]) * msecond

### Function: Remove Unit

In [50]:
q = [-1.0, 2.0] * bu.second
bm.sign(q)

Array([-1.,  1.], dtype=float64)

### Function: Logical

In [51]:
q1 = [1.0, 2.0] * bu.second
q2 = [1.0, 3.0] * bu.second
bm.isclose(q1, q2, atol=0.2)

Array([ True, False], dtype=bool)

### Function: Window

In [52]:
bm.bartlett(5)

Array([0. , 0.5, 1. , 0.5, 0. ], dtype=float64)

### Linear Algebra

In [53]:
q1 = [1, 2] * bu.second
q2 = [3, 4] * bu.volt
bm.dot(q1, q2)

11. * weber

### More Functions

In [54]:
q1 = [1, 2, 3] * bu.second
q2 = [4, 5] * bu.volt
bm.einsum('i,j->ij', q1, q2)

ArrayImpl([[ 4.,  5.],
           [ 8., 10.],
           [12., 15.]]) * weber

## Shape Manipulation

### Changing the shape of a Quantity

A Quantity has a shape given by the number of elements along each axis:


In [55]:
a = jnp.floor(10 * bst.random.random((3, 4))) * bu.mV
a

ArrayImpl([[6., 2., 0., 0.],
           [0., 0., 5., 5.],
           [2., 2., 3., 9.]]) * mvolt

In [56]:
a.shape

(3, 4)

The shape of a Quantity can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [57]:
a.ravel()  # returns the array, flattened

ArrayImpl([6., 2., 0., 0., 0., 0., 5., 5., 2., 2., 3., 9.]) * mvolt

In [58]:
a.reshape(6, 2) # returns the array with a modified shape

ArrayImpl([[6., 2.],
           [0., 0.],
           [0., 0.],
           [5., 5.],
           [2., 2.],
           [3., 9.]]) * mvolt

In [59]:
a.T  # returns the array, transposed

ArrayImpl([[6., 0., 2.],
           [2., 0., 2.],
           [0., 5., 3.],
           [0., 5., 9.]]) * mvolt

In [60]:
a.T.shape

(4, 3)

In [61]:
a.shape

(3, 4)

The order of the elements in the Quantity resulting from ravel is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0, 0] is a[0, 1]. If the Quantity is reshaped to some other shape, again the Quantity is treated as “C-style”. NumPy normally creates arrays stored in this order, so ravel will usually not need to copy its argument, but if the Quantity was made by taking slices of another Quantity or created with unusual options, it may need to be copied. The functions ravel and reshape can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

The reshape function only returns its argument with a modified shape, due to Jax's immutability. The resize method is not available in braincore.

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [62]:
a.reshape(3, -1)

ArrayImpl([[6., 2., 0., 0.],
           [0., 0., 5., 5.],
           [2., 2., 3., 9.]]) * mvolt

### Stacking together different Quantities

Several arrays can be stacked together along different axes:

In [63]:
a = jnp.floor(10 * bst.random.random((2, 2))) * bu.mV
a

ArrayImpl([[8., 6.],
           [6., 7.]]) * mvolt

In [64]:
b = jnp.floor(10 * bst.random.random((2, 2))) * bu.mV
b

ArrayImpl([[2., 5.],
           [8., 8.]]) * mvolt

In [65]:
bm.vstack((a, b))

ArrayImpl([[8., 6.],
           [6., 7.],
           [2., 5.],
           [8., 8.]]) * mvolt

In [66]:
bm.hstack((a, b))

ArrayImpl([[8., 6., 2., 5.],
           [6., 7., 8., 8.]]) * mvolt

The function column_stack stacks 1D Quantities as columns into a 2D Quantities. It is equivalent to hstack only for 2D Quantities:

In [67]:
bm.column_stack((a, b)) # with 2D arrays

ArrayImpl([[8., 6., 2., 5.],
           [6., 7., 8., 8.]]) * mvolt

In [68]:
a = jnp.array([4., 2.]) * bu.mV
b = jnp.array([2., 8.]) * bu.mV
bm.column_stack((a, b)) # returns a 2D array

ArrayImpl([[4., 2.],
           [2., 8.]]) * mvolt

In [69]:
bm.hstack((a, b)) # the result is different

ArrayImpl([4., 2., 2., 8.]) * mvolt

In [70]:
a[:, jnp.newaxis] # view `a` as a 2D column vector

ArrayImpl([[4.],
           [2.]]) * mvolt

In [71]:
bm.column_stack((a[:, jnp.newaxis], b[:, jnp.newaxis]))

ArrayImpl([[4., 2.],
           [2., 8.]]) * mvolt

In [72]:
bm.hstack((a[:, jnp.newaxis], b[:, jnp.newaxis])) # the result is the same

ArrayImpl([[4., 2.],
           [2., 8.]]) * mvolt

### Splitting one Quantity into several smaller ones

Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped Quantities to return, or by specifying the columns after which the division should occur:

In [73]:
a = jnp.floor(10 * bst.random.random((2, 12))) * bu.mV
a

ArrayImpl([[3., 4., 8., 4., 0., 6., 1., 3., 3., 2., 9., 5.],
           [3., 0., 4., 3., 7., 6., 6., 5., 5., 1., 7., 7.]]) * mvolt

In [74]:
bm.hsplit(a, 3) # Split a into 3

[ArrayImpl([[3., 4., 8., 4.],
            [3., 0., 4., 3.]]) * mvolt,
 ArrayImpl([[0., 6., 1., 3.],
            [7., 6., 6., 5.]]) * mvolt,
 ArrayImpl([[3., 2., 9., 5.],
            [5., 1., 7., 7.]]) * mvolt]

In [75]:
bm.hsplit(a, (3, 4)) # Split `a` after the third and the fourth column

[ArrayImpl([[3., 4., 8.],
            [3., 0., 4.]]) * mvolt,
 ArrayImpl([[4.],
            [3.]]) * mvolt,
 ArrayImpl([[0., 6., 1., 3., 3., 2., 9., 5.],
            [7., 6., 6., 5., 5., 1., 7., 7.]]) * mvolt]

## Comparing Quantities

The equality of `Quantity` objects is best tested using the `brainunit.math.allclose()` and `brainunit.math.isclose()` functions, which are unit-aware analogues of the numpy functions with the same name:

In [76]:
bm.allclose([1, 2] * bu.meter, [100, 200] * bu.cm)

Array(True, dtype=bool)

In [77]:
bm.isclose([1, 2] * bu.meter, [100, 20] * bu.cm)

Array([ True, False], dtype=bool)

The use of Python comparison operators is also supported(>, <, >=, <=, ==, !=) if the two `Quantity` objects have the same unit. If the two `Quantity` objects have different units, a `DimensionMismatchError` will be raised.

In [78]:
1 * bu.meter < 50 * bu.cm

False

In [79]:
from brainunit import DimensionMismatchError

try:
    1 * bu.meter < 50 * bu.second
except DimensionMismatchError as e:
    print(e)

Cannot perform comparison 1.0 < 50.0, units do not match (units are m and s).
